name: Check var

on:
    push:
    pull_request:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Build and Test with Docker Compose
              run: |
                  docker compose -f docker-compose.yml build
